# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20171119_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
